version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  AfterInstall:
    - location: scripts/install_docker.sh
      timeout: 900
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 900
