version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: sample-app
    IMAGE_TAG: latest
    ECS_CLUSTER: sample-cluster
    ECS_SERVICE: sample-service

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region me-central-1 |
        docker login --username AWS --password-stdin 767397902739.dkr.ecr.me-central-1.amazonaws.com
        
  build:
    commands:
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 767397902739.dkr.ecr.me-central-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - docker push 767397902739.dkr.ecr.me-central-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
